---
name: Release Front End
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build website
        run: |
          cd website/simdut-search-website
          npm install
          npm run build
      - name: Upload to S3
        run: aws s3 sync website/simdut-search-website/build/ s3://${{ secrets.S3_BUCKET_ORIGIN
          }} --delete
      - name: Invalidate Cloudfront Distribution Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID
          }} --paths "/*"
